### ISSUE TITLE
Add support for multiple macro arguments

### ISSUE THREAD

**Issue by ngppgn** [Thom1729/YAML-Macros#19]
Currently, each yaml-macro accepts a single argument. While this is already greatly enabling, the expressivity of the tool would be much improved if macros could be defined (and invoked) with multiple parameters.

Maybe the syntax for invoking macros with n argumentscould be <tag handle><macro name> (<value_1>,..., <value_n>)

**Comment by Thom1729** [comment]
If you pass an array to a macro, the engine should splat the array and pass multiple args:

```py
def mymacro(foo, bar):
    return foo + bar
```

```yaml
!mymacro [ x, y ]
```

```yaml
"xy"
```

Does this work for you?
